name: thyroid-classifier
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy
  - zarr
  - pytorch
  - pytorch-cuda=11.8
  - monai
  - fastapi
  - uvicorn
  - pip:
      - lighter-zoo==0.1.3 
      - huggingface-hub==0.33.1
      - mlflow
      - simpleitk
      - tifffile